config/routes.rb
ClarkKent::Engine.routes.draw do
  resources :reports do
    member do
      get :download_link
      post :clone
    end
  end
  resources :report_filters
  resources :report_columns
  resources :report_emails
  resources :user_report_emails
  root to: 'reports#index'
end

app/models/clark_kent/cloneable.rb
module ClarkKent
  module Cloneable
    def cloneable_attributes
      these_attrs = self.attributes.dup
      these_attrs.delete('id')
      these_attrs.delete('created_at')
      these_attrs.delete('updated_at')
      these_attrs
    end

    def reset_timestamps
      updated_at = nil
      created_at = nil
      self
    end

  end
end

app/models/clark_kent/date_filter_option.rb
module ClarkKent
  class DateFilterOption < ReportFilterOption
    def filter_params
      [param + '_from', param + '_until']
    end
  end
end

app/models/clark_kent/number_filter_option.rb
module ClarkKent
  class NumberFilterOption < ReportFilterOption
    def filter_params
      [param + '_min', param + '_max']
    end
  end
end

app/models/clark_kent/object_filter_option.rb
module ClarkKent
  class ObjectFilterOption < ReportFilterOption
    def filter_params
      [param]
    end
  end
end

app/models/clark_kent/report.rb
module ClarkKent
require 'aws-sdk-v1'
  # load the builders
  Dir.glob(Rails.root.join('app/models/reporting/*.rb')) { |file| load file }
  class Report < ActiveRecord::Base
    include ClarkKent::Cloneable
    include ForeignOffice::Broadcaster

    require_channel_presence


    SortDirections = {'ascending' => 'asc', 'descending' => 'desc'}

    attr_accessor :summary_row_storage, :report_result_url, :browser_tab_id

    belongs_to :sharing_scope, polymorphic: true
    has_many :report_filters, as: :filterable, dependent: :destroy
    has_many :report_columns, -> {order("clark_kent_report_columns.column_order").references(:report_columns)}, dependent: :destroy
    has_many :report_emails, dependent: :destroy
    has_many :report_email_filters, through: :report_emails, source: :report_filters

    scope :for, ->(resource_type) { where(resource_type: resource_type) }
    scope :shared, -> { where(sharing_scope_id: nil) }

    validates :sharing_scope_id, presence: true, if: ->(r) { r.sharing_scope_type.present? }
    validates :resource_type, presence: {message: 'You must choose a type.'}, allow_blank: false

    def self.send_report_to_s3(report_id, params)
      report_class = params[:report_class].constantize if params[:report_class]
      report_class ||= ::ClarkKent::Report

      reportable = report_class.find(report_id)
      is_email = 'ClarkKent::ReportEmail' == report_class.name
      report = is_email ? reportable.report : reportable
      query = reportable.get_query(params)
      row_count = reportable.get_query(params, true)
      bucket = AWS::S3::Bucket.new(ClarkKent.bucket_name)
      report_destination = bucket.objects[params[:report_result_name]]
      byte_count = 0
      temp_buffer = report.headers.to_csv
      offset = 0
      summary_rows = []
      some_left = true
      report_destination.write(estimated_content_length: row_count * 1000) do |buffer, bytes|
        while temp_buffer.length < bytes and some_left
          this_batch = query.offset(offset).limit(100)
          some_left = this_batch.each do |row|
            temp_buffer << report.report_columns.map{ |column| row[column.column_name] }.to_csv
          end.any?
          summary_rows.push report.summary_row(this_batch) if report.summary_row? and some_left
          offset += 100
        end
        if report.summary_row_storage.blank? and (!some_left)
          if report.summary_row? and summary_rows.any?
            summary_row_map = report.summary_row(summary_rows)
            report.summary_row_storage = report.report_columns.map do |col|
              summary_row_map.send col.column_name
            end
            temp_buffer << report.summary_row_storage.to_csv
          end
        end
        if temp_buffer.present?
          chunk = temp_buffer.slice!(0...bytes)
          buffer << chunk
        end
      end
      report.report_result_url = report_destination.url_for(
        :read,
        secure: true,
        response_content_type: 'text/csv',
        response_content_encoding: 'binary',
        response_content_disposition: 'attachment',
        expires: 60*60*24*30 #good for 30 days
      )
      if 'ClarkKent::Report' == report_class.name
        report.browser_tab_id = params[:browser_tab_id]
        report.broadcast_change
      end
      if is_email && 'login_required' == ClarkKent.email_security
        params[:report_result_name]
      else
        report.report_result_url.to_s
      end
    end

    def viable_report_columns
      @viable_report_columns ||= report_columns.to_a.select{|rc| column_options_for(rc.column_name).present? }
    end

    def viable_report_filters
      @viable_report_filters ||= report_filters.to_a.select{|rf| filter_options_for(rf.filter_name).present? }
    end

    def get_query(params, count = false)
      self.resource_class.report(params,self, count)
    end

    def resource_class
      @resource_class ||= self.resource_type.constantize
    end

    ## This ephemeral class allows us to create a row object that has the same attributes as the AR response
    ## to the query, including all the custom columns defined in the resource class report config.
    ## currently only used for the summary row, since we can't get that in the same AR query and have to
    ## add it to the collection after the query returns.
    def row_class
      report_columns = viable_report_columns
      @row_class ||= Class.new do
        report_columns.each do |report_column|
          attr_accessor report_column.column_name.to_sym
        end

        def initialize params = {}
          params.each { |key, value| send "#{key}=", value }
        end

        def [](key)
          self.send key
        end
      end
    end

    def sort_column
      @sort_column ||= viable_report_columns.detect{|rc| rc.report_sort.present?}
    end

    def sorter
      if self.sort_column
        sort_column_name = self.sort_column.column_name
        sort_direction = Report::SortDirections[sort_column.report_sort]
        ReportSort.new(order_column: sort_column_name, order_direction: sort_direction)
      end
    end

    def arel_includes
      viable_report_columns.map{|column|
        column_info = self.column_options_for(column.column_name)
        column_info.includes
        }.compact
    end

    def arel_joins
      viable_report_columns.map{|column|
        column_info = self.column_options_for(column.column_name)
        column_info.joins
        }.compact
    end

    def extra_scopes
      viable_report_columns.map{|column|
        column_info = self.column_options_for(column.column_name)
        column_info.extra_scopes
        }.flatten.compact
    end

    def extra_filters
      viable_report_columns.map{|column|
        column_info = self.column_options_for(column.column_name)
        column_info.where
        }.flatten.compact
    end

    def groups
      viable_report_columns.map{|column|
        column_info = self.column_options_for(column.column_name)
        column_info.group
        }.flatten.compact
    end

    ## These are the built-in filter params that define this report. They are merged at a later
    ## step with the runtime params entered by the user for a specific report run.
    ## nb. the sorter column here may be overridden by a runtime sort if requested by the user.
    def report_filter_params
      Hash[*viable_report_filters.map{|filter| filter.filter_match_params}.flatten].
        merge(order: self.sorter)
    end

    def select_clauses
      @selects = []
      viable_report_columns.each do |report_column|
        column_option = self.column_options_for(report_column.column_name)
        @selects.push column_option.custom_select if column_option.present? && column_option.custom_select.present?
      end
      viable_report_filters.each do |report_filter|
        column_option = self.column_options_for(report_filter.filter_name.to_sym)
        @selects.push column_option.custom_select if column_option.present? && column_option.custom_select.present?
      end
      @selects
    end

    def filter_options_for(filter_name)
      self.resource_class.report_filter_options.detect{|filter| filter.param == filter_name}
    end

    def column_options
      @column_options ||= self.resource_class.report_column_options
    end

    def column_options_for(column_name)
      if column_options.any?{|co| co.name == column_name.to_sym}
        column_options.detect{|co| co.name == column_name.to_sym}
      else
        column_name = column_name.to_s.split('_')[0..-2].join('_')
        if column_options.any?{|co| co.name ==  column_name.to_sym}
          column_options.detect{|co| co.name == column_name.to_sym}
        end
      end
    end

    def filter_kind(filter_name)
      self.filter_options_for(filter_name).kind
    end

    def date_filter_names
      self.resource_class.report_filter_options.select{|filter| 'date_filter' == filter.kind}.map{|filter| filter.param}
    end

    ## These are the filters available for defining a report for this resource. They do not include date
    ## filters as those only make sense at runtime, or in an auto-generated, timed emailed report.
    def available_filters
      self.available_email_filters.reject{|name| self.date_filter_names.include? name}
    end

    def available_filter_options
      self.available_filters.map{|filter_name| [self.filter_options_for(filter_name).label,filter_name]}
    end

    ## This is the full set of filter options for defining a report, including the date filters for
    ## an automatic, timed, emailed report.
    def available_email_filters
      self.resource_class.report_definition_options.reject{|name| (viable_report_filters.map(&:filter_name)).include? name}
    end

    def collection_for(filter_name)
      self.filter_options_for(filter_name).collection
    end

    ## These are the filters available at runtime, ie. not including the ones set to define this report.
    ## If updating the report, this is the set available to add as new report definition filters.
    def custom_filters
      self.resource_class.report_filter_options.select{|filter| viable_report_filters.map(&:filter_name).exclude? filter.param}
    end

    ## This is the set of columns not chosed to use in the report. These are the ones available to add
    ## when updating a report.
    def available_columns
      column_options.reject{|column| viable_report_columns.map(&:column_name).include? column.name.to_s}
    end

    def sortable?(column)
      column_info = self.column_options_for(column.column_name)
      column_info.present? && column_info.order_sql.present?
    end

    def sharing_scope_pretty
      (self.sharing_scope.try :name ) || 'Everyone'
    end

    def resource_type_pretty
      if self.resource_class.respond_to? :prettify_name
        self.resource_class.prettify_name.pluralize
      else
        self.resource_class.name.humanize
      end
    end

    def get_filter_class(params)

app/models/clark_kent/report_column.rb
module ClarkKent
	class ReportColumn < ActiveRecord::Base
	  include ClarkKent::Cloneable

		SummaryMethods = ['total','average']

		belongs_to :report

		scope :sorted, -> { order("clark_kent_report_columns.column_order") }
    validates :column_name, presence: true
    validates_with ReportColumnValidator
    
    def has_options?
      config_options.present?
    end

		def report_sort_pretty
			{'ascending' => 'A->Z','descending' => 'Z->A'}[self.report_sort]
		end

		def calculate_summary(values)
			return nil unless self.summary_method.present?
			calculator.new(values).calculate
		end

		def summarizable?
			config_options.summarizable
		end

    def sortable?
      config_options.order_sql.present?
    end

		def calculator
			('ClarkKent::' + summary_method.camelcase + 'Calculator').constantize
		end

    def name
      column_name
    end

    def config_options
      report.column_options_for(self.name.to_sym)
    end

    def link
      config_options.link
    end

    def time_zone_column
      config_options.time_zone_column
    end

    def time_format
      config_options.time_format
    end
	end

	class AbstractCalculator
    def initialize values
    	@values = values
    end
	end

	class TotalCalculator < AbstractCalculator
    def calculate
    	@values.sum
    end
	end

	class AverageCalculator < AbstractCalculator
    def calculate
    	if @values.length < 1
        return nil
      else
        return (@values.sum.to_f / @values.length)
      end
    end
	end
end

app/models/clark_kent/report_config.rb
module ClarkKent
  module ReportConfig
    include ClarkKent::Reportable
    def filter_config(params)
      filter_option_class = ('ClarkKent::' + ((params[:kind] + '_option').camelcase)).constantize
      filter_option_class.new(params)
    end

    def column_config(params)
      ClarkKent::ReportColumnConfig.new(params)
    end

  end
  class ReportColumnConfig
    attr_accessor :name, :order_sql, :custom_select, :link, :time_zone_column, :time_format, :summarizable, :includes, :joins, :extra_scopes, :where, :group
    def initialize params = {}
      params.each { |key, value| send "#{key}=", value }
    end

    def id
      name
    end
  end
end

app/models/clark_kent/report_date_filter.rb
module ClarkKent
  class ReportDateFilter < ReportFilter
    WeekDayOptions = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
    MonthDayOptions = ['beginning of month']
    DayOptions = WeekDayOptions + MonthDayOptions
    WeekPeriodOptions = {
      'previous week' => 'last_week',
      'same week' => 'this_week',
      'following week' => 'next_week'
    }
    MonthPeriodOptions = {
      'previous month' => 'last_month',
      'same month' => 'this_month',
      'following month' => 'next_month'
    }

    PeriodOptions = WeekPeriodOptions.merge MonthPeriodOptions

    Durations = ['day','week','two weeks','month']

    before_save :handle_filter_value

    def filter_match_params
      [[self.begin_param_name,self.begin_date],[self.end_param_name,self.end_date]]
    end

    def begin_param_name
      "#{self.filter_name}_from"
    end

    def end_param_name
      "#{self.filter_name}_until"
    end

    def begin_date
      @begin_date = Date.today
      direction, period = self.period_offset
      @begin_date = @begin_date.send(direction, 1.send(period)) if direction
      @begin_date = @begin_date.find_day(self.day_offset) if self.day_offset
      @begin_date
    end

    def day_offset
      return false if 'today' == self.kind_of_day
      self.kind_of_day.gsub(/ /,'_')
    end

    def period_offset
      direction, period = self.offset.split('_')
      direction = {'last' => '-', 'next' => '+', 'this' => false, '' => false}[direction.to_s]
      return [direction, period]
    end

    def end_date
      return self.begin_date if 'day' == self.duration
      return self.begin_date + 6.days if 'week' == self.duration
      return self.begin_date + 13.days if 'two weeks' == self.duration
      if Date::DAYNAMES.include? self.kind_of_day.capitalize
        return self.begin_date + 1.month
      else
        return self.begin_date.end_of_month
      end
    end

    def handle_filter_value
      if self.filter_value_1.present? and self.filter_value_2.present?
        self.filter_value = [filter_value_1, self.filter_value_2].join(' ')
      end
    end

    def offset_pretty
      self.class::PeriodOptions.rassoc(self.offset).first
    end

    def date_display
      "starts on #{self.kind_of_day} #{self.offset_pretty} for 1 #{self.duration}"
    end
  end
end

app/models/clark_kent/report_filter.rb
module ClarkKent
	class ReportFilter < ActiveRecord::Base
	  include ClarkKent::Cloneable

	  attr_accessor :filter_value_1, :filter_value_2
		belongs_to :filterable, polymorphic: true

		def filter_match_params
			[self.filter_match_param,self.filter_match_value]
		end

		def filter_match_param
			self.filter_name
		end

		def filter_match_value
			self.filter_value
		end

		def display_name
			self.filter_name
		end

	end
end

app/models/clark_kent/report_filter_error.rb
module ClarkKent
  class ReportFilterError < StandardError
  end
end

app/models/clark_kent/report_filter_option.rb
module ClarkKent
	class ReportFilterOption

		attr_accessor :param, :label, :collection, :kind, :select, :in_required_date_group, :date_requirement_override

    def initialize params = {}
      params.each { |key, value| send "#{key}=", value }
    end

		def label
			@label || @param
		end
	end
end

app/models/clark_kent/report_number_filter.rb
module ClarkKent
  class ReportNumberFilter < ReportFilter

    def filter_match_params
      [[self.min_param_name,self.min_value],[self.max_param_name,self.max_value]]
    end

    def min_param_name
      "#{self.filter_name}_min"
    end

    def max_param_name
      "#{self.filter_name}_max"
    end

  end
end

app/models/clark_kent/report_object_filter.rb
module ClarkKent
	class ReportObjectFilter < ReportFilter
	  include Cloneable

		def get_display_value
			if self.filter_value.to_i > 0
				self.filter_class.find(self.filter_value).name
			else
				self.filter_value
			end
		end

		def filter_class
			if self.filter_name =~ /_id/
				self.filter_name.split('_')[0..-2].join('_').camelcase.constantize
			end
		end

		def display_name
			if self.filter_class.present?
				self.filter_class.name.underscore.humanize
			else
				self.filter_name
			end
		end
	end
end

app/models/clark_kent/report_string_filter.rb
module ClarkKent
  class ReportStringFilter < ReportFilter
    include Cloneable
  end
end

app/views/clark_kent/report_filters/_date_filter_edit.html.erb
<%= f.input :kind_of_day, collection: ClarkKent::ReportDateFilter::DayOptions, label: 'Report start: what kind of day?',
			input_html: {data: {revealer: "true", sub_type: "FormFieldRevealer", revealer_children_id: "period_options_#{name}_#{f.object.object_id}"}} %>
<div data-revealer-target="period_options_<%= name %>_<%= f.object.object_id %>">
	<%= f.input :offset, collection: ClarkKent::ReportDateFilter::WeekPeriodOptions, include_blank: false, label: 'Report start: when?',
				wrapper_html: {'data-revealer-id' => "period_options_#{name}_#{f.object.object_id}", 'data-revealer-triggers' => "['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']"} %>
	<%= f.input :offset, collection: ClarkKent::ReportDateFilter::MonthPeriodOptions, include_blank: false, label: 'Report start: when?',
				wrapper_html: {'data-revealer-id' => "period_options_#{name}_#{f.object.object_id}", 'data-revealer-triggers' => "['beginning of month','beginning of week']"} %>
</div>
<%= f.input :duration, collection: ClarkKent::ReportDateFilter::Durations %>

app/views/clark_kent/report_filters/_date_filter_show.html.erb
<%= report_filter.date_display %>

app/views/clark_kent/report_filters/_form.html.erb
<div class="srow editing">
  <%= simple_form_for report_filter,
      as: report_filter,
      url: report_filter.new_record? ? report_filters_url : report_filter_url(report_filter),
      defaults: {
        wrapper_html: { class: 'span2'},
        input_html: { class: 'input-medium' },
        label_html: { class: 'quiet'}},
      html: {
        id: "report_filter_form_#{report_filter.object_id}",
        class: 'form-inline',
        data: {
          ajax_form: true,
          sub_type: "AddALineForm",
          ajax_target: report_filter.new_record? ? "#report_filter_list_#{dom_id(report_filter.filterable)}" : "#report_filter_#{report_filter.id}",
          error_target: "#new_report_filter_container_#{dom_id(report_filter.filterable)}",
          insert_method: report_filter.new_record? ? 'append' : 'html',
          container: dom_target(report_filter.filterable, :new_report_filter_container),
          ajax_flash: true } } do |f| %>
    <div class="scol one-third">
      <%= f.input :filterable_id, as: :hidden %>
      <%= f.input :filterable_type, as: :hidden %>
      <% if report_filter.new_record? %>
        <%= f.input :filter_name, collection: report_filter.filterable.available_filter_options,
              input_html:
                revealer("filter_value_options_#{report_filter.object_id}", highlander: true).merge(
                  id: "report_filter_filter_name_#{report_filter.object_id}"),
              include_blank: false %>
      <% else %>
        <div class="srow quiet">Filter Name</div>
        <div class="srow"><%= report_filter.filter_name %></div>
      <% end %>
    </div>
    <% if report_filter.new_record? %>
      <div class="scol one-third" <%= revealer_target_attrs("filter_value_options_#{report_filter.object_id}") %>>
        <% report_filter.filterable.available_filters.each do |name,label| %>
          <div <%= revealer_option_attrs("filter_value_options_#{report_filter.object_id}", trigger: name) %> id="filter_value_options_<%= name %>">
            <%= render partial: report_filter.filterable.filter_kind(name) + '_edit', locals: {f: f, report_filter: report_filter, name: name} %>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="scol one-third">
        <%= render partial: report_filter.filterable.filter_kind(report_filter.filter_name) + '_edit', locals: {f: f, report_filter: report_filter, name: report_filter.filter_name} %>
      </div>
    <% end %>
    <div class="scol right margin-top">
      <%= f.button :submit %>
      <% if report_filter.new_record? %>
        &nbsp; <a <%= emptier dom_target(report_filter.filterable, :new_report_filter_container) %>> cancel </a>
      <% else %>
        &nbsp; <%= link_to 'cancel', report_filter_url(report_filter),
          data: {ajax_link: "true", ajax_target: "#report_filter_#{report_filter.id}"} %>
        &nbsp; <%= link_to '&otimes;'.html_safe, report_filter_url(report_filter), class: "delete", data: {ajax_delete: "true", ajax_target: "#report_filter_#{report_filter.id}" }, tabindex: "-1" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/clark_kent/report_filters/_index.html.erb
<div id="report_filter_container_<%= dom_id(filterable) %>">
  <h3><%= filterable.class.name.sub('ClarkKent::','').underscore.humanize %> Filters</h3>
  <div id="report_filter_list_<%= dom_id(filterable) %>" class="srow">
    <% for report_filter in filterable.viable_report_filters %>
      <%= render partial: '/clark_kent/report_filters/show_wrapper', locals: {report_filter: report_filter} %>
    <% end %>
  </div>

  <div class="srow margin-top">
    <%= link_to 'Add a Filter', new_report_filter_url(filterable_id: filterable.id, filterable_type: filterable.class.name), class: 'btn btn-primary', data: {ajax_link: "true", ajax_target: "#new_report_filter_container_#{dom_id(filterable)}" } %>
  </div>

  <div id="<%= dom_id filterable, :new_report_filter_container %>" class="srow margin-top">

  </div>
</div>

app/views/clark_kent/report_filters/_number_filter_edit.html.erb
<%= f.input :min_value %>
<%= f.input :max_value %>

app/views/clark_kent/report_filters/_number_filter_show.html.erb
<%= report_filter.min_value %> - <%= report_filter.max_value %>

app/views/clark_kent/report_filters/_object_filter_edit.html.erb
<%= f.input :filter_value, collection: collection_for(report_filter, name) %>

app/views/clark_kent/report_filters/_object_filter_show.html.erb
<%= report_filter.get_display_value %>

app/views/clark_kent/report_filters/_show.html.erb
<div class="srow read-only report-element">
	<div class="scol one-third">
		<%= report_filter.display_name %> ->
	</div>
	<div class="scol one-third">
		<%= render partial: '/clark_kent/report_filters/' + report_filter.filterable.filter_kind(report_filter.filter_name) + '_show', locals: {report_filter: report_filter} %>
	</div>
	<div class="scol right">
		<%= link_to 'edit', edit_report_filter_url(report_filter),
				data: {
					ajax_link: true,
					ajax_target: "#report_filter_#{report_filter.id}" } %>
	</div>
</div>

app/views/clark_kent/report_filters/_show_wrapper.html.erb
<div id="report_filter_<%= report_filter.id %>">
	<%= render partial: '/clark_kent/report_filters/show', locals: {report_filter: report_filter} %>
</div>

app/views/clark_kent/report_filters/_string_filter_show.html.erb
<%= report_filter.filter_value %>