config/routes.rb
ClarkKent::Engine.routes.draw do
  resources :reports do
    member do
      get :download_link
      post :clone
    end
  end
  resources :report_filters
  resources :report_columns
  resources :report_emails
  resources :user_report_emails
  root to: 'reports#index'
end

app/models/clark_kent/cloneable.rb
module ClarkKent
  module Cloneable
    def cloneable_attributes
      these_attrs = self.attributes.dup
      these_attrs.delete('id')
      these_attrs.delete('created_at')
      these_attrs.delete('updated_at')
      these_attrs
    end

    def reset_timestamps
      updated_at = nil
      created_at = nil
      self
    end

  end
end

app/models/clark_kent/date_filter_option.rb
module ClarkKent
  class DateFilterOption < ReportFilterOption
    def filter_params
      [param + '_from', param + '_until']
    end
  end
end

app/models/clark_kent/number_filter_option.rb
module ClarkKent
  class NumberFilterOption < ReportFilterOption
    def filter_params
      [param + '_min', param + '_max']
    end
  end
end

app/models/clark_kent/object_filter_option.rb
module ClarkKent
  class ObjectFilterOption < ReportFilterOption
    def filter_params
      [param]
    end
  end
end

app/models/clark_kent/report.rb
module ClarkKent
require 'aws-sdk-v1'
  # load the builders
  Dir.glob(Rails.root.join('app/models/reporting/*.rb')) { |file| load file }
  class Report < ActiveRecord::Base
    include ClarkKent::Cloneable
    include ForeignOffice::Broadcaster

    require_channel_presence


    SortDirections = {'ascending' => 'asc', 'descending' => 'desc'}

    attr_accessor :summary_row_storage, :report_result_url, :browser_tab_id

    belongs_to :sharing_scope, polymorphic: true
    has_many :report_filters, as: :filterable, dependent: :destroy
    has_many :report_columns, -> {order("clark_kent_report_columns.column_order").references(:report_columns)}, dependent: :destroy
    has_many :report_emails, dependent: :destroy
    has_many :report_email_filters, through: :report_emails, source: :report_filters

    scope :for, ->(resource_type) { where(resource_type: resource_type) }
    scope :shared, -> { where(sharing_scope_id: nil) }

    validates :sharing_scope_id, presence: true, if: ->(r) { r.sharing_scope_type.present? }
    validates :resource_type, presence: {message: 'You must choose a type.'}, allow_blank: false

    def self.send_report_to_s3(report_id, params)
      report_class = params[:report_class].constantize if params[:report_class]
      report_class ||= ::ClarkKent::Report

      reportable = report_class.find(report_id)
      is_email = 'ClarkKent::ReportEmail' == report_class.name
      report = is_email ? reportable.report : reportable
      query = reportable.get_query(params)
      row_count = reportable.get_query(params, true)
      bucket = AWS::S3::Bucket.new(ClarkKent.bucket_name)
      report_destination = bucket.objects[params[:report_result_name]]
      byte_count = 0
      temp_buffer = report.headers.to_csv
      offset = 0
      summary_rows = []
      some_left = true
      report_destination.write(estimated_content_length: row_count * 1000) do |buffer, bytes|
        while temp_buffer.length < bytes and some_left
          this_batch = query.offset(offset).limit(100)
          some_left = this_batch.each do |row|
            temp_buffer << report.report_columns.map{ |column| row[column.column_name] }.to_csv
          end.any?
          summary_rows.push report.summary_row(this_batch) if report.summary_row? and some_left
          offset += 100
        end
        if report.summary_row_storage.blank? and (!some_left)
          if report.summary_row? and summary_rows.any?
            summary_row_map = report.summary_row(summary_rows)
            report.summary_row_storage = report.report_columns.map do |col|
              summary_row_map.send col.column_name
            end
            temp_buffer << report.summary_row_storage.to_csv
          end
        end
        if temp_buffer.present?
          chunk = temp_buffer.slice!(0...bytes)
          buffer << chunk
        end
      end
      report.report_result_url = report_destination.url_for(
        :read,
        secure: true,
        response_content_type: 'text/csv',
        response_content_encoding: 'binary',
        response_content_disposition: 'attachment',
        expires: 60*60*24*30 #good for 30 days
      )
      if 'ClarkKent::Report' == report_class.name
        report.browser_tab_id = params[:browser_tab_id]
        report.broadcast_change
      end
      if is_email && 'login_required' == ClarkKent.email_security
        params[:report_result_name]
      else
        report.report_result_url.to_s
      end
    end

    def viable_report_columns
      @viable_report_columns ||= report_columns.to_a.select{|rc| column_options_for(rc.column_name).present? }
    end

    def viable_report_filters
      @viable_report_filters ||= report_filters.to_a.select{|rf| filter_options_for(rf.filter_name).present? }
    end

    def get_query(params, count = false)
      self.resource_class.report(params,self, count)
    end

    def resource_class
      @resource_class ||= self.resource_type.constantize
    end

    ## This ephemeral class allows us to create a row object that has the same attributes as the AR response
    ## to the query, including all the custom columns defined in the resource class report config.
    ## currently only used for the summary row, since we can't get that in the same AR query and have to
    ## add it to the collection after the query returns.
    def row_class
      report_columns = viable_report_columns
      @row_class ||= Class.new do
        report_columns.each do |report_column|
          attr_accessor report_column.column_name.to_sym
        end

        def initialize params = {}
          params.each { |key, value| send "#{key}=", value }
        end

        def [](key)
          self.send key
        end
      end
    end

    def sort_column
      @sort_column ||= viable_report_columns.detect{|rc| rc.report_sort.present?}
    end

    def sorter
      if self.sort_column
        sort_column_name = self.sort_column.column_name
        sort_direction = Report::SortDirections[sort_column.report_sort]
        ReportSort.new(order_column: sort_column_name, order_direction: sort_direction)
      end
    end

    def arel_includes
      viable_report_columns.map{|column|
        column_info = self.column_options_for(column.column_name)
        column_info.includes
        }.compact
    end

    def arel_joins
      viable_report_columns.map{|column|
        column_info = self.column_options_for(column.column_name)
        column_info.joins
        }.compact
    end

    def extra_scopes
      viable_report_columns.map{|column|
        column_info = self.column_options_for(column.column_name)
        column_info.extra_scopes
        }.flatten.compact
    end

    def extra_filters
      viable_report_columns.map{|column|
        column_info = self.column_options_for(column.column_name)
        column_info.where
        }.flatten.compact
    end

    def groups
      viable_report_columns.map{|column|
        column_info = self.column_options_for(column.column_name)
        column_info.group
        }.flatten.compact
    end

    ## These are the built-in filter params that define this report. They are merged at a later
    ## step with the runtime params entered by the user for a specific report run.
    ## nb. the sorter column here may be overridden by a runtime sort if requested by the user.
    def report_filter_params
      Hash[*viable_report_filters.map{|filter| filter.filter_match_params}.flatten].
        merge(order: self.sorter)
    end

    def select_clauses
      @selects = []
      viable_report_columns.each do |report_column|
        column_option = self.column_options_for(report_column.column_name)
        @selects.push column_option.custom_select if column_option.present? && column_option.custom_select.present?
      end
      viable_report_filters.each do |report_filter|
        column_option = self.column_options_for(report_filter.filter_name.to_sym)
        @selects.push column_option.custom_select if column_option.present? && column_option.custom_select.present?
      end
      @selects
    end

    def filter_options_for(filter_name)
      self.resource_class.report_filter_options.detect{|filter| filter.param == filter_name}
    end

    def column_options
      @column_options ||= self.resource_class.report_column_options
    end

    def column_options_for(column_name)
      if column_options.any?{|co| co.name == column_name.to_sym}
        column_options.detect{|co| co.name == column_name.to_sym}
      else
        column_name = column_name.to_s.split('_')[0..-2].join('_')
        if column_options.any?{|co| co.name ==  column_name.to_sym}
          column_options.detect{|co| co.name == column_name.to_sym}
        end
      end
    end

    def filter_kind(filter_name)
      self.filter_options_for(filter_name).kind
    end

    def date_filter_names
      self.resource_class.report_filter_options.select{|filter| 'date_filter' == filter.kind}.map{|filter| filter.param}
    end

    ## These are the filters available for defining a report for this resource. They do not include date
    ## filters as those only make sense at runtime, or in an auto-generated, timed emailed report.
    def available_filters
      self.available_email_filters.reject{|name| self.date_filter_names.include? name}
    end

    def available_filter_options
      self.available_filters.map{|filter_name| [self.filter_options_for(filter_name).label,filter_name]}
    end

    ## This is the full set of filter options for defining a report, including the date filters for
    ## an automatic, timed, emailed report.
    def available_email_filters
      self.resource_class.report_definition_options.reject{|name| (viable_report_filters.map(&:filter_name)).include? name}
    end

    def collection_for(filter_name)
      self.filter_options_for(filter_name).collection
    end

    ## These are the filters available at runtime, ie. not including the ones set to define this report.
    ## If updating the report, this is the set available to add as new report definition filters.
    def custom_filters
      self.resource_class.report_filter_options.select{|filter| viable_report_filters.map(&:filter_name).exclude? filter.param}
    end

    ## This is the set of columns not chosed to use in the report. These are the ones available to add
    ## when updating a report.
    def available_columns
      column_options.reject{|column| viable_report_columns.map(&:column_name).include? column.name.to_s}
    end

    def sortable?(column)
      column_info = self.column_options_for(column.column_name)
      column_info.present? && column_info.order_sql.present?
    end

    def sharing_scope_pretty
      (self.sharing_scope.try :name ) || 'Everyone'
    end

    def resource_type_pretty
      if self.resource_class.respond_to? :prettify_name
        self.resource_class.prettify_name.pluralize
      else
        self.resource_class.name.humanize
      end
    end

    def get_filter_class(params)

app/models/clark_kent/report_column.rb
module ClarkKent
	class ReportColumn < ActiveRecord::Base
	  include ClarkKent::Cloneable

		SummaryMethods = ['total','average']

		belongs_to :report

		scope :sorted, -> { order("clark_kent_report_columns.column_order") }
    validates :column_name, presence: true
    validates_with ReportColumnValidator
    
    def has_options?
      config_options.present?
    end

		def report_sort_pretty
			{'ascending' => 'A->Z','descending' => 'Z->A'}[self.report_sort]
		end

		def calculate_summary(values)
			return nil unless self.summary_method.present?
			calculator.new(values).calculate
		end

		def summarizable?
			config_options.summarizable
		end

    def sortable?
      config_options.order_sql.present?
    end

		def calculator
			('ClarkKent::' + summary_method.camelcase + 'Calculator').constantize
		end

    def name
      column_name
    end

    def config_options
      report.column_options_for(self.name.to_sym)
    end

    def link
      config_options.link
    end

    def time_zone_column
      config_options.time_zone_column
    end

    def time_format
      config_options.time_format
    end
	end

	class AbstractCalculator
    def initialize values
    	@values = values
    end
	end

	class TotalCalculator < AbstractCalculator
    def calculate
    	@values.sum
    end
	end

	class AverageCalculator < AbstractCalculator
    def calculate
    	if @values.length < 1
        return nil
      else
        return (@values.sum.to_f / @values.length)
      end
    end
	end
end

app/models/clark_kent/report_config.rb
module ClarkKent
  module ReportConfig
    include ClarkKent::Reportable
    def filter_config(params)
      filter_option_class = ('ClarkKent::' + ((params[:kind] + '_option').camelcase)).constantize
      filter_option_class.new(params)
    end

    def column_config(params)
      ClarkKent::ReportColumnConfig.new(params)
    end

  end
  class ReportColumnConfig
    attr_accessor :name, :order_sql, :custom_select, :link, :time_zone_column, :time_format, :summarizable, :includes, :joins, :extra_scopes, :where, :group
    def initialize params = {}
      params.each { |key, value| send "#{key}=", value }
    end

    def id
      name
    end
  end
end

app/models/clark_kent/report_date_filter.rb
module ClarkKent
  class ReportDateFilter < ReportFilter
    WeekDayOptions = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
    MonthDayOptions = ['beginning of month']
    DayOptions = WeekDayOptions + MonthDayOptions
    WeekPeriodOptions = {
      'previous week' => 'last_week',
      'same week' => 'this_week',
      'following week' => 'next_week'
    }
    MonthPeriodOptions = {
      'previous month' => 'last_month',
      'same month' => 'this_month',
      'following month' => 'next_month'
    }

    PeriodOptions = WeekPeriodOptions.merge MonthPeriodOptions

    Durations = ['day','week','two weeks','month']

    before_save :handle_filter_value

    def filter_match_params
      [[self.begin_param_name,self.begin_date],[self.end_param_name,self.end_date]]
    end

    def begin_param_name
      "#{self.filter_name}_from"
    end

    def end_param_name
      "#{self.filter_name}_until"
    end

    def begin_date
      @begin_date = Date.today
      direction, period = self.period_offset
      @begin_date = @begin_date.send(direction, 1.send(period)) if direction
      @begin_date = @begin_date.find_day(self.day_offset) if self.day_offset
      @begin_date
    end

    def day_offset
      return false if 'today' == self.kind_of_day
      self.kind_of_day.gsub(/ /,'_')
    end

    def period_offset
      direction, period = self.offset.split('_')
      direction = {'last' => '-', 'next' => '+', 'this' => false, '' => false}[direction.to_s]
      return [direction, period]
    end

    def end_date
      return self.begin_date if 'day' == self.duration
      return self.begin_date + 6.days if 'week' == self.duration
      return self.begin_date + 13.days if 'two weeks' == self.duration
      if Date::DAYNAMES.include? self.kind_of_day.capitalize
        return self.begin_date + 1.month
      else
        return self.begin_date.end_of_month
      end
    end

    def handle_filter_value
      if self.filter_value_1.present? and self.filter_value_2.present?
        self.filter_value = [filter_value_1, self.filter_value_2].join(' ')
      end
    end

    def offset_pretty
      self.class::PeriodOptions.rassoc(self.offset).first
    end

    def date_display
      "starts on #{self.kind_of_day} #{self.offset_pretty} for 1 #{self.duration}"
    end
  end
end

app/models/clark_kent/report_filter.rb
module ClarkKent
	class ReportFilter < ActiveRecord::Base
	  include ClarkKent::Cloneable

	  attr_accessor :filter_value_1, :filter_value_2
		belongs_to :filterable, polymorphic: true

		def filter_match_params
			[self.filter_match_param,self.filter_match_value]
		end

		def filter_match_param
			self.filter_name
		end

		def filter_match_value
			self.filter_value
		end

		def display_name
			self.filter_name
		end

	end
end

app/models/clark_kent/report_filter_error.rb
module ClarkKent
  class ReportFilterError < StandardError
  end
end

app/models/clark_kent/report_filter_option.rb
module ClarkKent
	class ReportFilterOption

		attr_accessor :param, :label, :collection, :kind, :select, :in_required_date_group, :date_requirement_override

    def initialize params = {}
      params.each { |key, value| send "#{key}=", value }
    end

		def label
			@label || @param
		end
	end
end

app/models/clark_kent/report_number_filter.rb
module ClarkKent
  class ReportNumberFilter < ReportFilter

    def filter_match_params
      [[self.min_param_name,self.min_value],[self.max_param_name,self.max_value]]
    end

    def min_param_name
      "#{self.filter_name}_min"
    end

    def max_param_name
      "#{self.filter_name}_max"
    end

  end
end

app/models/clark_kent/report_object_filter.rb
module ClarkKent
	class ReportObjectFilter < ReportFilter
	  include Cloneable

		def get_display_value
			if self.filter_value.to_i > 0
				self.filter_class.find(self.filter_value).name
			else
				self.filter_value
			end
		end

		def filter_class
			if self.filter_name =~ /_id/
				self.filter_name.split('_')[0..-2].join('_').camelcase.constantize
			end
		end

		def display_name
			if self.filter_class.present?
				self.filter_class.name.underscore.humanize
			else
				self.filter_name
			end
		end
	end
end

app/models/clark_kent/report_string_filter.rb
module ClarkKent
  class ReportStringFilter < ReportFilter
    include Cloneable
  end
end

app/views/clark_kent/reports/_date_filter.html.erb
<div class="scol one-quarter report-filter">
	<div class="srow">
		<b><%= filter.label.humanize %></b>
	</div>
	<div class="srow">
		<div class="scol">
		  from<br>
		  <%= date_field_tag "#{filter.param}_from",
		            params["#{filter.param}_from"],
		            data: {date_picker: 'true'},
		            class: 'string input-small',
		            id: "#{filter.param}_start_date" %>
		</div>
		<div class="scol">
		  to<br>
		  <%= date_field_tag "#{filter.param}_until",
		          params["#{filter.param}_until"],
		          data: {date_picker: 'true'},
		          class: 'string input-small',
		          id: "#{filter.param}_end_date" %>
		</div>
	</div>
</div>

app/views/clark_kent/reports/_download_link.html.erb
<% if @report_result_name %>
	<%= link_to 're-download full csv', '',
			data: listener_hash(@report, :report_result_url, browser_tab_id: @browser_tab_id, trigger: true ) %>
<% else %>
	<%= link_to 'download full csv', (download_link_report_url(@report.id) + '?' + request.query_parameters.to_param),
			data: {
				ajax_link: true,
				ajax_target: '#download_link' } %>
<% end %>

app/views/clark_kent/reports/_edit.html.erb
<div class="srow">
  <%= simple_form_for @report, html: @report.persisted? ? ajax_form_hash( '#report_info_container' ) : {} do |f| %>
    <div class="scol one-quarter">
      <%= f.input :name, minlength: false %>
    </div>
    <div class="scol one-quarter">
      <%= f.input :resource_type,
          collection: ClarkKent.resource_options,
          label: 'A row for every:',
          prompt: 'Please Choose' %>

    </div>
    <%= f.input :sharing_scope_type, as: :hidden, value: 'Everyone' %>
    <%= f.input :sharing_scope_id, as: :hidden, value: 'Everyone' %>
    <div class="scol one-quarter margin-top right">
      <div class="srow">
        <%= f.button :submit %>
        <% unless @report.new_record? %>
            &nbsp; <%= ajax_link 'cancel', report_url(@report), {class: 'right'}, "#report_info_container" %>
          </div>
          <div class="srow right">or</div>
          <div class="srow">
            <%= link_to "Delete Report", @report, class: 'right', :method=>:delete, :data => { delete_link: true, :confirm => "Are you sure you want to delete this report?" } %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/clark_kent/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :resource_type %><br>
    <%= f.text_field :resource_type %>
  </div>
  <div class="field">
    <%= f.label :sharing_scope_type %><br>
    <%= f.text_field :sharing_scope_type %>
  </div>
  <div class="field">
    <%= f.label :sharing_scope_id %><br>
    <%= f.number_field :sharing_scope_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clark_kent/reports/_number_filter.html.erb
<div class="scol one-quarter report-filter">
	<div class="srow">
		<b><%= filter.label.humanize %></b>
	</div>
	<div class="srow">
		<div class="scol">
		  min<br>
		  <%= text_field_tag "#{filter.param}_min",
		            params["#{filter.param}_min"],
		            class: 'string input-small',
		            id: "#{filter.param}_min" %>
		</div>
		<div class="scol">
		  max<br>
		  <%= text_field_tag "#{filter.param}_max",
		          params["#{filter.param}_max"],
		          class: 'string input-small',
		          id: "#{filter.param}_max" %>
		</div>
	</div>
</div>

app/views/clark_kent/reports/_object_filter.html.erb
<div class="scol one-quarter report-filter">
	<div class="srow">
		<b><%= filter.param.humanize %></b>
	</div>
	<div class="srow">
		<% options = case filter.collection.class.name
			 when 'String', 'Symbol'
			   clark_kent_user.send(filter.collection)
			 when 'Array', 'ActiveRecord::Relation'
			   filter.collection
			 end %>
		<%= select_tag filter.param,
			options_from_collection_for_select(
				options,
				(select_value_method(filter.param,options.first)),
				(select_text_method(filter.param,options.first)),
				params[filter.param]), {include_blank: true}.merge((options.length > 25) ? {'data-autocomplete' => true} : {}) %>

	</div>
</div>

app/views/clark_kent/reports/_print_report.html.erb
<% if rows %>
  <% if rows.total_count > 50 %>
    <div <%= modal_trigger("#print_report_modal", dismissable: true) %> class="link"> Print </div>
    <div id="print_report_modal" class="hidden">
      <p> You will only be printing the current page of results (<%= @report.resource_class.default_per_page %> of <%= @rows.total_count %> total results).
          To print all results click the <strong>download full csv</strong> link at the bottom of the page.</p>
      <div class="row-fluid" >
        <div class="span8"></div>
        <div class="span1">
          <%= print_button(@rows, true) %>
        </div>
      </div>
    </div>
  <% else %>
    <%= print_button(@rows) %>
  <% end %>
<% end %>

app/views/clark_kent/reports/_show.html.erb
<div class="scol one-quarter">
	<%= @report.name %>
</div>
<div class="scol one-quarter">
	<span class="quiet">a row for every</span> <%= @report.resource_type_pretty.singularize %>
</div>
<div class="scol one-quarter">
	<span class="quite">shared with</span> <%= @report.sharing_scope_pretty %>
</div>
<div class="scol one-quarter right">
  <%= link_to 'clone', clone_report_url(@report),
      method: :post,
      style: 'margin-left: 10px',
      class: 'right' %>

	<%= link_to 'edit', edit_report_url(@report),
    data: {
			ajax_link: true,
			ajax_target: '#report_info_container' },
			class: 'right' %>
</div>

app/views/clark_kent/reports/_string_filter.html.erb
<div class="scol one-quarter report-filter">
	<div class="srow">
		<b><%= filter.param.humanize %></b>
	</div>
	<div class="srow">
		<%= text_field_tag filter.param, params[filter.param] %>

	</div>
</div>

app/views/clark_kent/reports/edit.html.erb
<h1> Editing report: <%= @report.name %></h1>
<%= link_to "&larr; back to report index".html_safe, reports_url %>


<div class="srow margin-top">
	<div id="report_info_container">
		<%= render partial: 'show' %>
	</div>
</div>

<% unless @report.new_record? %>
	<div class="well srow">
		<%= render partial: '/clark_kent/report_filters/index', locals: {filterable: @report} %>
	</div>
	<div class="well srow">
		<%= render partial: '/clark_kent/report_columns/index' %>
	</div>
	<div class="well srow">
		<%= render partial: '/clark_kent/report_emails/index' %>
	</div>
<% end %>

app/views/clark_kent/reports/index.html.erb
<h1>Reports</h1>
<% ClarkKent::Report.all.each do |report| %>
  <%= link_to report.name, report_url(report) %> <%= link_to '(edit)', edit_report_url(report) %><br>
<% end %>
<hr>
<div id="controls">
  <%= link_to "create a new report", new_report_path %>
</div>

app/views/clark_kent/reports/new.html.erb
<h1>Create a new report.</h1>
<%= link_to "&larr; back to report index".html_safe, reports_url %>


<div class="srow margin-top">
	<div id="report_info_container">
		<%= render partial: 'edit' %>
	</div>
</div>

app/views/clark_kent/reports/show.html.erb
<h1><%= @report.name %></h1>
<%= link_to "&larr; back to report index".html_safe, reports_url, id: 'report_index' %>
<%= controller_name %>
<% if @errors %>
	<div class="error">
		<%= @errors %>
	</div>
<% end %>
<div class="srow margin-top">
	<form action="<%= report_url(@report) %>" method="get">
		<% @report.custom_filters.each do |filter| %>
			<%= render partial: filter.kind, locals: {filter: filter} %>
		<% end %>
		<input type="hidden" name="run_report" value="true">
		<%= button_tag 'Run Report', class: 'btn', style: 'margin-left: 0px' %>
		<%= render partial: 'print_report', locals: {rows: @rows} %>
	</form>
</div>
<% if @rows %>
	<div class="srow margin-top">
		<table class="stripey-table">
			<tr>
				<% @report.report_columns.sorted.each do |column| %>
					<th>
						<%=
							@report.sortable?(column) ?
								(link_to column.column_name, request.path + '?' + request.query_parameters.merge(order: "#{column.column_name}-#{get_temp_order_direction(params)}").to_param) :
								column.column_name.humanize %> <%= get_selected_order_direction(params, column)
						%>
					</th>
				<% end %>
			</tr>
			<% @rows.each do |row| %>
				<tr>
					<% @report.report_columns.each do |column| %>
						<td><%= display_for_value(row[column.column_name], column, row) %></td>
					<% end %>
				</tr>
			<% end %>
		</table>
	</div>
	<div class="srow margin-top">
	  <%= paginate @rows %>
	  <div id="download_link"><%= render partial: 'download_link' %></div>
	</div>
<% end %>
<div class="scol">&nbsp;</div>